In [1]:
import numpy as np
from Matrix import Matrix
from gauss import SoleSolver, gauss_inv, cond, residual

In [2]:
# 3
A = Matrix([[2, 2, -1, 1],
            [-3, 0, 3, 0],
            [-1, 3, 3, 2],
            [1, 0, 0, 4]])
b = Matrix([[3],
            [-9],
            [-7],
            [4]])

In [3]:
x = SoleSolver().solve(A, b)
r = residual(A, x, b)
print("My solution:", x, sep='\n')
print("Numpy solution:", np.linalg.solve(A.values, b.values), sep='\n')
print("Residual\n", r)

My solution:
[4.0]
[-2.0]
[1.0]
[0.0]
Numpy solution:
[[ 4.00000000e+00]
 [-2.00000000e+00]
 [ 1.00000000e+00]
 [-2.22044605e-16]]
Residual
 [0.0]
[0.0]
[0.0]
[0.0]


In [18]:
# 4
A = Matrix([[-7, -6, -6, 6],
            [7, 6, 8, -13],
            [4, 17, -16, 10],
            [-4, 18, 19, 0]])
b = Matrix([[144],
            [-170],
            [21],
            [-445]])

In [19]:
x = SoleSolver().solve(A, b)
r = residual(A, x, b)
print("My solution:", x, sep='\n')
print("Numpy solution:", np.linalg.solve(A.values, b.values), sep='\n')
print("Residual\n", r)

My solution:
[3.8838054872867188e-16]
[-11.000000000000004]
[-13.000000000000002]
[-7.050921875993813e-16]
Numpy solution:
[[-2.03012210e-15]
 [-1.10000000e+01]
 [-1.30000000e+01]
 [-5.85064159e-16]]
Residual
 [5.684341886080802e-14]
[-5.684341886080802e-14]
[-3.552713678800501e-14]
[-1.1368683772161603e-13]


In [20]:
# 6
A = Matrix([[5, 0, -7, 0],
            [-1, 6, 0, 1],
            [2, -6, -4, -5],
            [-6, -6, 15, 7]])
b = Matrix([[-123],
            [60],
            [-108],
            [159]])

In [22]:
x = SoleSolver().solve(A, b)
# r = residual(A, x, b)
print("My solution:", x, sep='\n')
print("Numpy solution:", np.linalg.solve(A.values, b.values), sep='\n')
# print("Residual\n", r)

My solution:
None
Numpy solution:
[[-29.23076923]
 [  3.79487179]
 [ -3.30769231]
 [  8.        ]]
