In [1]:
import numpy as np
from Matrix import Matrix
from gauss import SoleSolver, gauss_inv, cond, residual

In [2]:
# 3
A1 = Matrix([[2, 2, -1, 1],
            [-3, 0, 3, 0],
            [-1, 3, 3, 2],
            [1, 0, 0, 4]])
b1 = Matrix([[3],
            [-9],
            [-7],
            [4]])

In [3]:
x1 = SoleSolver().solve(A1, b1)
r1 = residual(A1, x1, b1)
print("My solution:", x1, sep='\n')
print("Numpy solution:", np.linalg.solve(A1.values, b1.values), sep='\n')
print("Residual\n", r1)

My solution:
[4.0]
[-2.0]
[1.0]
[0.0]
Numpy solution:
[[ 4.00000000e+00]
 [-2.00000000e+00]
 [ 1.00000000e+00]
 [-2.22044605e-16]]
Residual
 [0.0]
[0.0]
[0.0]
[0.0]


In [4]:
# 4
A2 = Matrix([[-7, -6, -6, 6],
            [7, 6, 8, -13],
            [4, 17, -16, 10],
            [-4, 18, 19, 0]])
b2 = Matrix([[144],
            [-170],
            [21],
            [-445]])

In [5]:
x2 = SoleSolver().solve(A2, b2)
r2 = residual(A2, x2, b2)
print("My solution:", x2, sep='\n')
print("Numpy solution:", np.linalg.solve(A2.values, b2.values), sep='\n')
print("Residual\n", r2)

My solution:
[3.8838054872867188e-16]
[-11.000000000000004]
[-13.000000000000002]
[-7.050921875993813e-16]
Numpy solution:
[[-2.03012210e-15]
 [-1.10000000e+01]
 [-1.30000000e+01]
 [-5.85064159e-16]]
Residual
 [5.684341886080802e-14]
[-5.684341886080802e-14]
[-3.552713678800501e-14]
[-1.1368683772161603e-13]


In [6]:
# 6
A3 = Matrix([[5, 0, -7, 0],
            [-1, 6, 0, 1],
            [2, -6, -4, -5],
            [-6, -6, 15, 7]])
b3 = Matrix([[-123],
            [60],
            [-108],
            [159]])

In [7]:
x3 = SoleSolver().solve(A3, b3)
# r = residual(A, x, b)
print("My solution:", x3, sep='\n')
print("Numpy solution:", np.linalg.solve(A3.values, b3.values), sep='\n')
# print("Residual\n", r)

My solution:
None
Numpy solution:
[[-29.23076923]
 [  3.79487179]
 [ -3.30769231]
 [  8.        ]]


In [8]:
# 8: Condition number
print(f"My cond A1: {cond(A1)} | Numpy cond: {np.linalg.cond(A1.values, p=1)}")
print(f"My cond A2: {cond(A2)} | Numpy cond: {np.linalg.cond(A2.values, p=1)}")
print(f"My cond A3: {cond(A3)} | Numpy cond: {np.linalg.cond(A3.values, p=1)}")

My cond A1: 77.0 | Numpy cond: 77.00000000000003
My cond A2: 28.940949893912197 | Numpy cond: 28.940949893912194
Singular matrix: Conditional number cannot be calculated
My cond A3: -1 | Numpy cond: 1.5274708736164938e+17


In [11]:
# 10
perturbation = Matrix([[-.001],
                       [.003],
                       [-.0028],
                       [-.0002]])
x1 = SoleSolver().solve(A1, b1 + perturbation)
r1 = residual(A1, x1, b1 + perturbation)
print("My solution:", x1, sep='\n')
print("Numpy solution:", np.linalg.solve(A1.values, (b1 + perturbation).values), sep='\n')
print("Residual\n", r1)

My solution:
[3.984600000000002]
[-1.9942000000000009]
[0.9856000000000021]
[0.0037999999999995073]
Numpy solution:
[[ 3.9846e+00]
 [-1.9942e+00]
 [ 9.8560e-01]
 [ 3.8000e-03]]
Residual
 [0.0]
[0.0]
[0.0]
[0.0]


In [12]:
x2 = SoleSolver().solve(A2, b2 + perturbation)
r2 = residual(A2, x2, b2 + perturbation)
print("My solution:", x2, sep='\n')
print("Numpy solution:", np.linalg.solve(A2.values, (b2 + perturbation).values), sep='\n')
print("Residual\n", r2)

My solution:
[-8.487677492789465e-05]
[-10.999999203525384]
[-13.000029149665416]
[-0.00029404276154476475]
Numpy solution:
[[-8.48767749e-05]
 [-1.09999992e+01]
 [-1.30000291e+01]
 [-2.94042762e-04]]
Residual
 [5.684341886080802e-14]
[-2.842170943040401e-14]
[-3.907985046680551e-14]
[-1.1368683772161603e-13]


In [13]:
x3 = SoleSolver().solve(A3, b3 + perturbation)
# r = residual(A, x, b)
print("My solution:", x3, sep='\n')
print("Numpy solution:", np.linalg.solve(A3.values, (b3 + perturbation).values), sep='\n')
# print("Residual\n", r)

My solution:
None
Numpy solution:
[[-1.77834447e+12]
 [-4.34000733e+11]
 [-1.27024605e+12]
 [ 8.25659932e+11]]


Control questions:

1.
> Скільки множень/ділень потребує виконання алгоритму Гауса?
 
$\frac{n(n+1)}{2}$ делений, $\frac{2n^3+3n^2-5n}{6}$ умножений. Асимптотическая сложность: $O(n^3)$.

2.
> Покажіть, що алгоритм Гауса без перестановок рядків (схема основного поділу) не приводить до успіху, коли один з головних мінорів вихідної матриці дорівнює нулю.

Допустим $a_{ii}=0$. Тогда, $\frac{a_{ki}}{a_{ii}}$ неопределено. Решение: на шаге $i$ выбрать такое $t \in (i, n]$ такое что $a_{ti} != 0$, переставить строку $i$ и $t$. Если такого $t$ нет, матрица вырождена.

3.
>Проаналізуйте, як накопичуються похибки заокруглень в коефіцієнтах СЛАР при її претвореннях методом Гауса. Доведіть, що саме перестановка рівнянь призводить до появи таких Гаусових множників, які мінімізують можливе накопичення похибок заокруглення.

При каждом выполнении $a_{k} = a_{k} - \frac{a_ki}{a_{ii}}$ мы считаем разницу между одинаковыми величинами $\delta(a-b)$, ошибка в которой "может быть сколь угодно большой". Ошибка накапливается с прохождением алгоритма -- для $a_n = (n-1)\delta(a-b)$. Переставляя строки для $a_{ii} \approx 0$, мы избегаем умножения на число с плавающей запятой "до последнего".

4.
>Чому визначник трикутної матриці дорівнює добутку діагональних елементів?

$$det(\begin{bmatrix}
        a_{11} & a_{12} & \dots & a_{1n} \\
        0      &  a_{22} & \dots & a_{2n} \\
        \vdots &  \dots & \ddots & \dots \\
        0      &  \dots &  \dots & a_{nn}
      \end{bmatrix})=a_{11}det(\begin{bmatrix}
        a_{22} & a_{23} & \dots & a_{2n} \\
        0      &  a_{33} & \dots & a_{3n} \\
        \vdots &  \dots & \ddots & \dots \\
        0      &  \dots &  \dots & a_{nn}
      \end{bmatrix})=\dots=a_{11}a_{22}\dots a_{nn}$$
5.
> Що таке норма вектора?

Норма вектора - это функционал $p: V \rightarrow R$ такой что:
1. $p(x) = 0 \Rightarrow x = 0_V$
2. $\forall_{x,y \in V}p(x + y) \le p(x) + p(y)$
3. $\forall{\alpha \in C},\forall{x \in V} p(\alpha x) = |\alpha|p(x)$

6.
> Що таке норма матриці?

Такой же функционал, определённый для линейного пространства $K^{m\times{n}}, K=[R|C]$. Каждой матрице $A \in K^{m\times n}$ ставится неотрицательное действительное число $||A||$, такое что:
1. $ ||A|| = \begin{cases} 
      0 & A = 0 \\
      > 0 & A \ne 0 
   \end{cases}
$
2. $||A+B||\le ||A|| + ||B||, A,B \in K^{m\times n}$
3. $||\alpha A|| = |\alpha|||A||, \alpha \in K, A \in K^{m \times n}$

7.
> Що таке число обумовленості матриці?

Число обусловленности это функционал $p: A \rightarrow R, A \in K^{m \times n}$ такой, что $p(A)=||A||||A^{-1}||$. Оно ассоциируется с системой линейных уравнений $Ax=b$, и даёт оценку того насколько возмущение $b$ влияет на вектор решения $x$. Чем оно больше, тем более "неустойчиво" наше решение. 

8.
> З якими складностями пов’язане обчислення числа обумовленості матриці за формулою?

Если матрица $A$ сингулярна, возникает проблема нахождения обратной матрицы.