In [2]:
from gauss import SoleSolver, gauss_inv, cond
from Matrix import Matrix

In [8]:
A = Matrix([[-7, -6, -6, 6],
                [7, 6, 8, -13],
                [4, 17, -16, 10],
                [-4, 18, 19, 0]])
b = Matrix([[144],
                [-170],
                [21],
                [-445]])
x = SoleSolver().solve(A, b)

In [15]:
import numpy as np
np.linalg.cond(A.values, p=float('inf'))

19.467373918720416

In [16]:
cond(A, float('inf'))

19.467373918720423

In [17]:
A @ x

[144.00000000000006]
[-170.00000000000006]
[20.999999999999964]
[-445.0000000000001]

In [18]:
x.T @ x

[290.0000000000001]

In [11]:
import numpy as np

In [12]:
np.linalg.solve(A.values, b.values)

array([[-29.23076923],
       [  3.79487179],
       [ -3.30769231],
       [  8.        ]])

In [13]:
A = Matrix([[2, 2, -1, 1],
           [-3, 0, 3, 0],
           [-1, 3, 3, 2],
           [1, 0, 0, 4]])
b = Matrix([[3], [-9], [-7], [4]])

In [14]:
np.linalg.solve(A.values, b.values)

array([[ 4.00000000e+00],
       [-2.00000000e+00],
       [ 1.00000000e+00],
       [-2.22044605e-16]])

In [15]:
solve_gauss(A, b)

[4.0]
[-2.0]
[1.0]
[0.0]

In [16]:
A = Matrix([[-7, -6, -6, 6],
            [7, 6, 8, -13],
            [4, 17, -16, 10],
            [-5, 18, 19, 0]])
b = Matrix([[144], [-170], [21], [-445]])

In [17]:
np.linalg.solve(A.values, b.values)

array([[ 2.03012210e-15],
       [-1.10000000e+01],
       [-1.30000000e+01],
       [ 5.87654283e-16]])

In [18]:
solve_gauss(A, b)

[2.563351794623059e-16]
[-11.000000000000004]
[-13.000000000000002]
[-6.8146825147828e-16]

In [19]:
A = Matrix([[1, 2], [2, 4]])
b = Matrix([[1], [2]])

In [21]:
solve_gauss(A, b)

ValueError: Singular matrix

In [35]:
np.linalg.solve(A.values, b.values)

LinAlgError: Singular matrix