In [5]:
from gauss import solve_gauss, gauss_inv, condition_number
from Matrix import Matrix

In [6]:
import sys

class SoleSolver:
    def __init__(self):
        pass
    
    def isclose(self, a, b, rel_tol=1e-09, abs_tol=.0):
        return abs(a - b) <= max(rel_tol * max(abs(a), abs(b)), abs_tol)
    
    def solve(self, A, b):
        nrow, ncol = A.shape if len(A.shape) == 2 else (A.shape, None)
        X = A[:, :]  # Make a copy (needed for np.array)
        b = b[:, :]  # Make a copy
        for i in range(min((nrow, ncol))):
            if self.isclose(X[i, i], 0):  # find row with non-zero on the pivot place, swap
                for j in range(i + 1, nrow):
                    if not self.isclose(X[j, i], 0):
                        X[i, :], X[j, :] = X[j, :], X[i, :]
                        b[i, :], b[j, :] = b[j, :], b[i, :]
                        break
            if not self.isclose(X[i, i], 1) and not self.isclose(X[i, i], 0.0):
                k = X[i, i]  # scale factor
                X[i, :] /= k  # scale coefficients
                b[i, :] /= k  # scale free term

            for j in range(i + 1, nrow):  # Remove corresponding coef. in other equations
                if not self.isclose(X[j, i], 0):
                    k = X[j, i]  # scale factor
                    X[j, :] -= X[i, :] * k
                    b[j, :] -= b[i, :] * k
            for j in range(i - 1, -1, -1):  # remove coef. above the main diagonal
                if not self.isclose(X[j, i], 0):
                    k = X[j, i]
                    X[j, :] -= X[i, :] * k
                    b[j, :] -= b[i, :] * k
        
        return X, b

In [7]:
A = Matrix([[5, 0, -7, 0],
            [-1, 6, 0, 1],
            [2, -6, -4, -5],
            [-6, -6, 15, 7]])
b = Matrix([[-123],
            [60],
            [-108],
            [159]])
x = solve_gauss(A, b)

In [14]:
import numpy as np
np.linalg.cond(A.values)

1.7243862250898556e+16

In [15]:
condition_number(A)

NotImplementedError: 

In [4]:
A @ x

[-123.0]
[59.99999999999999]
[-108.0]
[159.0]

In [10]:
x.T @ x

[3913.6811308349756]

In [11]:
import numpy as np

In [12]:
np.linalg.solve(A.values, b.values)

array([[-29.23076923],
       [  3.79487179],
       [ -3.30769231],
       [  8.        ]])

In [13]:
A = Matrix([[2, 2, -1, 1],
           [-3, 0, 3, 0],
           [-1, 3, 3, 2],
           [1, 0, 0, 4]])
b = Matrix([[3], [-9], [-7], [4]])

In [14]:
np.linalg.solve(A.values, b.values)

array([[ 4.00000000e+00],
       [-2.00000000e+00],
       [ 1.00000000e+00],
       [-2.22044605e-16]])

In [15]:
solve_gauss(A, b)

[4.0]
[-2.0]
[1.0]
[0.0]

In [16]:
A = Matrix([[-7, -6, -6, 6],
            [7, 6, 8, -13],
            [4, 17, -16, 10],
            [-5, 18, 19, 0]])
b = Matrix([[144], [-170], [21], [-445]])

In [17]:
np.linalg.solve(A.values, b.values)

array([[ 2.03012210e-15],
       [-1.10000000e+01],
       [-1.30000000e+01],
       [ 5.87654283e-16]])

In [18]:
solve_gauss(A, b)

[2.563351794623059e-16]
[-11.000000000000004]
[-13.000000000000002]
[-6.8146825147828e-16]

In [19]:
A = Matrix([[1, 2], [2, 4]])
b = Matrix([[1], [2]])

In [21]:
solve_gauss(A, b)

ValueError: Singular matrix

In [35]:
np.linalg.solve(A.values, b.values)

LinAlgError: Singular matrix